object_preselection:
  Jet:
    pt_raw: 8 
    eta: 10 
    jetId: 0 
  JetPuppiMET:
    pt: 10
    eta: 10 
    jetId: 0 
  JetPNet:
    pt: 10
    eta: 10
    jetId: 0
  JetPNetPlusNeutrino:
    pt: 10
    eta: 10
    jetId: 0

  GenJet:
    pt: 10 
    eta: 10 
    
    
    
    
